version: "3.3"

services:
  demo:
    image: registry.xmin-cloud.guru/xmin/application:latest
    ports:
      - 3000:3000
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == worker